# Generated by Django 4.2.5 on 2024-03-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
