# Generated by Django 4.2.5 on 2024-03-18 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_user_delete_users_student_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
