# Generated by Django 4.2.5 on 2024-03-19 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_student_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='registered',
        ),
    ]
