# Generated by Django 4.2.5 on 2024-03-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_remove_student_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='editmode',
            field=models.BooleanField(default=False),
        ),
    ]
