# Generated by Django 4.2.5 on 2024-03-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_student_editmode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='editmode',
        ),
    ]
